# Generated by Django 2.2.14 on 2023-01-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMapp', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Description about item'),
            preserve_default=False,
        ),
    ]
