# Generated by Django 2.2.14 on 2023-01-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WMapp', '0006_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Sc', 'Select city'), ('Ha', 'Hama'), ('Dm', 'Damascus'), ('Al', 'Aleppo'), ('Hm', 'Homs'), ('Lt', 'Latakia'), ('Tr', 'Tartus'), ('Dr', 'Daraa'), ('Su', 'Al-Suwayda'), ('Hs', 'Al-Hasakah'), ('Qm', 'Al-Qamishli'), ('Rq', 'Al-Raqqah'), ('Qu', 'Al-Qunaytirah'), ('Dz', 'Dayr al-Zawr'), ('Id', 'Idlib')], max_length=2)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='WMapp.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='WMapp.Address'),
        ),
    ]
