# Generated by Django 2.2.14 on 2023-01-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMapp', '0008_auto_20230109_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
