# Generated by Django 2.2.14 on 2023-01-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMapp', '0009_remove_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
