# Generated by Django 2.2.14 on 2023-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMapp', '0013_auto_20230110_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
