# Generated by Django 2.2.14 on 2023-01-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMapp', '0016_auto_20230110_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('MN', 'Men'), ('WN', 'Wemen'), ('KD', 'Kids'), ('SH', 'Shose'), ('HM', 'Home'), ('BG', 'Bage'), ('JL', 'Jewelry'), ('WT', 'WATCHES')], max_length=2),
        ),
    ]
