# Generated by Django 2.2.14 on 2023-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMapp', '0017_auto_20230111_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('RD', 'RED'), ('BL', 'BLUE'), ('GR', 'GREEN')], default='R', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'SMALL'), ('L', 'LARG'), ('M', 'MEDIUM'), ('XL', 'XLARG')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
